theme: jekyll-theme-slate
title: [Compounds relevant in Archaeology]
description: [A GC-HRMS spectra database]
show_downloads: [true]
github:
  zip_url: https://github.com/gc-hrms-spectra/gc-hrms-spectra.github.io/blob/master/src/databases/Archaeology_GC_HRMS_Spectra_Database.json
  tar_url: https://github.com/gc-hrms-spectra/gc-hrms-spectra.github.io/blob/master/src/databases/Archaeology_GC_HRMS_Spectra_Database.json
