theme: jekyll-theme-slate
title: Compounds relevant in Archaeology
description: A GC-HRMS spectral database
show_downloads: [true]
github:
  download_url: https://github.com/gc-hrms-spectra/Database-of-archeological-relevant-compounds/blob/dev/Archaeology_GC_HRMS_Spectra_Database.json